# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rspec_samplee_development

test:
  <<: *default
  database: rspec_samplee_test

production:
  <<: *default
  database: rspec_samplee_production
  username: rspec_samplee
  password: <%= ENV['rspec_samplee_DATABASE_PASSWORD'] %>